[programs.localnet]
macroswap = "HppM1iaYCKDMjpdtxg96eRsK45Q3uFhCVhjsNnJa4VgQ"

[programs.devnet]
macroswap = "HppM1iaYCKDMjpdtxg96eRsK45Q3uFhCVhjsNnJa4VgQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/riomain/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
