[programs.localnet]
macroswap = "6AReeFQXs4i26mt8rGco188gX21cFTaqnhHpgxHaEH6j"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/riomain/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
